name: Laravel (Sail)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Set Laravel Sail Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Start Sail (Build containers)
        run: ./vendor/bin/sail up -d
        env:
          WWWGROUP: 1000
          WWWUSER: 1000

      - name: Wait for services to be ready
        run: sleep 20

      - name: Generate application key
        run: ./vendor/bin/sail artisan key:generate

      - name: Run Laravel Tests via Sail
        run: ./vendor/bin/sail test
