name: Run PHPUnit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, bcmath, mysql, redis, xml, curl
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=2G

    - name: Install composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Setup environment file
      run: |
        cp .env.testing .env
        php -r "
          \$env = file_get_contents('.env');
          \$env = preg_replace('/DB_CONNECTION=.*/', 'DB_CONNECTION=mysql', \$env);
          \$env = preg_replace('/DB_HOST=.*/', 'DB_HOST=127.0.0.1', \$env);
          \$env = preg_replace('/DB_PORT=.*/', 'DB_PORT=3306', \$env);
          \$env = preg_replace('/DB_DATABASE=.*/', 'DB_DATABASE=laravel', \$env);
          \$env = preg_replace('/DB_USERNAME=.*/', 'DB_USERNAME=sail', \$env);
          \$env = preg_replace('/DB_PASSWORD=.*/', 'DB_PASSWORD=password', \$env);
          file_put_contents('.env', \$env);
        "
        php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -P 3306 -u sail -ppassword && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --testdox